name: Upload to PyPI

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install YJViewer
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade build twine
        python -m pip install -e .[dev,test]
    - name: Lint
      run: |
        pre-commit run --all-files
    - name: Build Distributions
      run: |
        python -m build
    - name: Upload to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_KEY }}
      run: |
        python -m twine upload dist/*
